baseURL: "https://weizhang-econ.github.io/"
title: Wei Zhang
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: /papers/
          weight: 1
        - name: About Me
          url: cv/
          weight: 3
        - name: Teaching
          url: courses/
          weight: 2
    #    - name: US Policy Rates
    #      url: policy/
    #      weight: 4
        - name: News
          url: news/
          weight: 4
        
##        - name: Newsletter
##          url: https://pmichaillat.substack.com
#          weight: 4

params:
    description: "I am a Postdoctoral Fellow in Economics at Johns Hopkins University."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Wei Zhang
          subtitle: "Welcome to my website! I am a Postdoctoral Fellow in Economics at Johns Hopkins University.
           <br>  <br> My research currently focuses on developing high-dimensional time series models for empirical macroeconomics or financial economics, including **large Bayesian VARs**, **dynamic factor models**, and **stochastic volatility models**. In general, I am interested in **Bayesian model comparison**, **time series models** and **variational inference**. "
          # <br>  <br> **I am on the 2024-2025 job market.**
          imageUrl: "/photo_square.png"
          imageWidth: 200
          imageHeight: 200
          imageTitle: Wei Zhang
          buttons:
            - name: Job Market Paper
              url: papers/JMP_WeiZhang_Aug25.pdf            
            
            - name: Research
              url: papers/
            - name: Teaching
              url: courses/
            - name: About Me
              url: cv/
#            - name: US Policy Rates
#              url: policy/
            - name: News
              url: news/
#            - name: About Me
#              url: about/
#            - name: Newsletter
#              url: https://pmichaillat.substack.com
#            - name: Tags
#              url: tags/
#            - name: Archive
#              url: archive/
    socialIcons:
        - name: CV
          url: CV_1111.pdf
        - name: Email
          url: mailto:wei.katie.zhang@gmail.com
        - name: Location
          url: location/
#        - name: Office Hours
#          url: officehours/
#        - name: Google Scholar
#          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
#        - name: YouTube
#          url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/weizhang-econ
#        - name: Substack
#          url: https://pmichaillat.substack.com
#        - name: Twitter
#          url: https://twitter.com/pmichaillat

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Wei Zhang"
      icon: /favicon-whale.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
